//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerpointGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerpointGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet opgeslagen wegens te lang pad.
        /// </summary>
        internal static string Form1_Niet_opgeslagen_wegens_te_lang_pad {
            get {
                return ResourceManager.GetString("Form1_Niet_opgeslagen_wegens_te_lang_pad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liturgie bestanden|*.liturgie.
        /// </summary>
        internal static string Form1_Openen_liturgie_filter {
            get {
                return ResourceManager.GetString("Form1_Openen_liturgie_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies bestand.
        /// </summary>
        internal static string Form1_Openen_liturgie_title {
            get {
                return ResourceManager.GetString("Form1_Openen_liturgie_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerpoint bestand (*.ppt)|*.ppt|Powerpoint bestanden (*.pptx)|*.pptx.
        /// </summary>
        internal static string Form1_Opslaan_pp_filter {
            get {
                return ResourceManager.GetString("Form1_Opslaan_pp_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sla de presentatie op.
        /// </summary>
        internal static string Form1_Opslaan_pp_title {
            get {
                return ResourceManager.GetString("Form1_Opslaan_pp_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap visitekaartje {
            get {
                object obj = ResourceManager.GetObject("visitekaartje", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
